# @package _global_
data_type: audio_diffusion_256
model_type: score_model

scheme_params:
  beta_case: vanilla
  decay_case: vanilla_sigma
  nb_time_steps_eval: 400

training_params:
  epochs: 100
  batch_size: 4
  batch_size_eval: 8
  check_val_every_n_epochs: 2
  lr: 1e-4
  weight_decay: 1e-6
  betas: [0.95, 0.999]
  accumulate_grad_batches: 4
  ema_dict:
    use_ema: True
    decay: 0.9999
    use_ema_warmup: True
    power: 0.75
  gradient_clip_val: 1.0

model_params:
  embedding_type: fourier
  n_channels: 128
  ch_mult: [1, 1, 2, 2, 4, 4]
  n_resblocks: 2

checkpoint_dict:
  save_top: 3