# @package _global_
defaults:
  - rl/rl_base
  - _self_
  
data_type: "maze2d_umaze_v1"

scheme_params:
  conditioning_case: "conditioning_rl_first_last"

training_params:
  epochs: 800
  check_val_every_n_epochs: 50
  batch_size: 64
  batch_size_eval: 64
  
model_params:
  transition_dim: 6
  horizon: 240
  dim: 240
  dim_mults: [1, 2, 2]
  attention: false

