# @package _global_
defaults:
  - _self_
  
model_type: d3pm
n_samples: 100000
data_type: swissroll_discrete
accelerator: cpu

training_params:
  epochs: 200  
  check_val_every_n_epochs: 10

scheme_params:
  nb_time_steps_train: 800
  nb_time_steps_eval: 800
  transition_case: uniform
  store_transition_matrices: False
  seq_length: 2

model_params:
  nb_tokens: 50
  emb_dim: 32
  nb_heads: 2
  hidden_dim: 32
  nb_layers: 3
  dropout: 0.0


